task :run_tests do
  require_relative 'TicTacToeRuby.Core.UnitTests/Players/tc_player_type.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Players/tc_player_type.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Players/tc_player_manager_initialization.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Players/tc_player_manager.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Players/tc_player.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Players/tc_player_movement_manager.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/GamePlay/tc_match_type.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/GamePlay/tc_match_type_manager.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/GamePlay/tc_game_board.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/GamePlay/tc_computer_actions.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Validators/tc_available_spaces_validation.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Validators/tc_game_over_validation.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Validators/tc_game_play_validation.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Validators/tc_player_selection_validation.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Validators/tc_player_symbol_validation.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Validators/tc_tie_game_validation.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Evaluators/tc_board_score_evaluation_parameterized_tests.rb'
  ruby 'TicTacToeRuby.Core.UnitTests/Evaluators/tc_board_score_evaluation.rb'
  ruby 'TicTacToeRuby.Console.UnitTests/Players/tc_first_player_setup.rb'
  ruby 'TicTacToeRuby.Console.UnitTests/GamePlay/tc_game_interaction.rb'
end
