welcome: "Welcome to Tic Tac Toe! Let's play a game!"
language_configuration_prompt: "Would you like to change languages? "
language_configuration_option: "If so, press L."
language_selection_prompt: "Which language do you want to use?"
player_symbol_prompt: "Let's setup Player number [1]! Press a key that Player [1] can use in the game. It can be a letter or a symbol."
continue_prompt: "Press any key to continue..."
undo_last_move_option: "OR type the letter U to undo the last move."
game_over: "Game Over!"
tie_game: "No winners this time. It's a tie!"
exit_game: "Press the letter E to exit the game. Goodbye!"
player_won: "Player [1] won! Good game!"
players_intro: "Players: [1] [ [2] ], [3] [ [4] ]"
board_intro: "Tic Tac Toe Board:\n"
board_square_selection: "Player [1] picked spot [2]!"
undo_completion_for_one_player: "Undo complete!"
undo_completion_for_both_players: "Undo complete for both players!"
thinking_process_for_computers_turn: "Player [1]'s Turn: Player is thinking of next move..."
thinking_process_incrementor: "."
next_move_prompt: "Player [1]'s Turn: Where do you want to move?\nType a number that you see on the board."
first_player_of_game_prompt: "Who should play first, [1] or [2]?"
match_selection_prompt: "Who is playing? Please select one of the matches below:\n"
match_option_description: "[1] Vs [2]"
option_number: "[1]. "
title_of_player_setup_screen: "Player Setup"
title_of_match_setup_screen: "Match Setup"
title_of_language_options_screen: "Language Setup"
argument_error: "Cannot [1] because [2] is [3]."
uniqueness_error: "Oops! I can't use the same one. Try again."
invalid_selection_error: "Oops! I couldn't use that. Please try another key."
invalid_selection_error_for: "Oops! I couldn't use that for the setup of [1]. Please try another key."
language_defaults_error: "ERROR: Unable to use language stored in global settings. Configure it manually."
line_spacer: "\n" 