welcome: "¡Bienvenido a Tic Tac Toe! ¡Juguemos!"
language_configuration: "[Presione L para cambiar el idioma.]"
language_selection_prompt: "¿Qué idioma quieres usar?"
player_symbol_prompt: "Vamos a configurar el número de jugador [1]! Presiona una tecla que el jugador [1] puede usar en el juego. Puede ser una letra o un simbolo."
continue_prompt: "Pulse cualquier tecla para continuar..."
undo_last_move_option: "O escriba la letra U para deshacer el último movimiento."
game_over: "¡Juego terminado!"
tie_game: "No hay ganadores esta vez. ¡Es un empate!"
exit_game: "Presione la letra E para salir del juego. ¡Adiós!"
player_won: "Jugador [1] ganó! ¡Buen juego!"
players_intro: "Jugadores: [1] [ [2] ], [3] [ [4] ]"
board_intro: "Tic Tac Toe Tablero:\n"
board_square_selection: "¡Jugador [1] seleccionado cuadrado [2]!"
undo_completion_for_one_player: "Deshacer completo!"
undo_completion_for_both_players: "Deshacer completo para ambos jugadores!"
thinking_process_for_computers_turn: "Turno del jugador [1]: el jugador está pensando en el siguiente movimiento..."
thinking_process_incrementor: "."
next_move_prompt: "Turno del jugador [1]: ¿Dónde quieres moverte?\nEscriba un número que vea en el tablero."
first_player_of_game_prompt: "¿Quién debería jugar primero, [1] o [2]?"
match_selection_prompt: "¿Quien esta jugando? Seleccione una de las siguientes partidos:\n"
match_option_description: "[1] Vs [2]"
option_number: "[1]. "
argument_error: "No se puede [1] porque [2] es [3]."
uniqueness_error: "Oops! No puedo usar el mismo Inténtalo de nuevo."
invalid_selection_error: "Oops! No podría usar eso. Intente con otra clave."
line_spacer: "\n" 